import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import useSWR from "swr";
import Link from "next/link";
import styled from "styled-components";
import { StyledLink } from "@/components/StyledComponents/StyledLink";

const inter = Inter({ subsets: ["latin"] });

const MapWithNoSSR = dynamic(() => import("@/components/Map/Map"), {
  ssr: false,
});
const FixedLink = styled(StyledLink)`
  position: fixed;
  bottom: 50px;
  right: 50px;
`;
export default function Home() {
  const { data, isLoading } = useSWR("/api/restaurants");

  if (isLoading) <h1>Loading...</h1>;

  if (!data) {
    return;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MapWithNoSSR restaurants={data} />
        <div className={styles.center}>
          <Link href="/create" passHref legacyBehavior>
            <FixedLink>+ restaurant</FixedLink>
          </Link>
        </div>
      </main>
    </>
  );
}
